"""
Astra capability engine — language-agnostic static-analysis parsers.

Everything in this module is deterministic. There are no LLM calls: complexity,
nesting depth, library usage, and boilerplate classification are all derived from
a concrete syntax/abstract-syntax tree. Python is handled by the standard-library
:mod:`ast` module; C/C++/CUDA, JavaScript, and TypeScript are handled by
py-tree-sitter grammars.

Public surface:

* :class:`BaseCodeParser` — the abstract interface every parser implements.
* :class:`PythonParser` — native ``ast`` implementation.
* :class:`TreeSitterParser` — py-tree-sitter implementation (cpp/js/ts/tsx).
* :func:`get_parser` — factory that picks a parser by file extension.

The parsers expose two library-facing methods:

* :meth:`BaseCodeParser.detected_libraries` — ``{lib: intensity}`` per the engine
  contract, where intensity is the number of genuine reference sites.
* :meth:`BaseCodeParser.library_usage` — richer per-library facts
  (``call_sites`` and ``kernel_authoring``) consumed by
  :func:`services.library_registry.detect_deep_usage`.
"""

from __future__ import annotations

import ast
import os
import re
from abc import ABC, abstractmethod
from functools import lru_cache

from services.library_registry import LIB_WEIGHTS

# ---------------------------------------------------------------------------
# Shared configuration
# ---------------------------------------------------------------------------

# Import tokens that should resolve to a registry library under a different
# canonical name. e.g. `import cupy` is CUDA-adjacent GPU work.
IMPORT_ALIASES: dict[str, str] = {
    "cupy": "cuda",
    "pycuda": "cuda",
    "torch_xla": "xla",
}

# Lexical markers that mean "a human did not hand-write the meaningful logic
# here". Presence of any is a strong boilerplate signal regardless of language.
_GENERATED_MARKERS = (
    "do not edit",
    "generated by",
    "autogenerated",
    "auto-generated",
    "@generated",
    "this file was automatically generated",
    "code generated by",
)

# Commit-message tokens that hint the change was scaffolding rather than logic.
_BOILERPLATE_COMMIT_TOKENS = (
    "boilerplate",
    "scaffold",
    "generated",
    "autogenerated",
    "initial commit",
    "chore: init",
    "bootstrap",
    "template",
)

# Extension -> logical language identifier used by the factory.
_EXT_LANGUAGE: dict[str, str] = {
    ".py": "python",
    ".cpp": "cpp",
    ".cc": "cpp",
    ".cxx": "cpp",
    ".hpp": "cpp",
    ".hxx": "cpp",
    ".h": "cpp",
    ".cu": "cpp",   # CUDA is C++-with-extensions; the cpp grammar parses it.
    ".cuh": "cpp",
    ".js": "javascript",
    ".jsx": "javascript",
    ".mjs": "javascript",
    ".cjs": "javascript",
    ".ts": "typescript",
    ".tsx": "tsx",
}


def _resolve_lib(module_root: str) -> str | None:
    """Map an import token to a canonical registry library name, if any."""
    canonical = IMPORT_ALIASES.get(module_root, module_root)
    return canonical if canonical in LIB_WEIGHTS else None


# ---------------------------------------------------------------------------
# Abstract interface
# ---------------------------------------------------------------------------
class BaseCodeParser(ABC):
    """Language-agnostic contract for a single parsed source file."""

    def __init__(self, source: str, file_path: str = "") -> None:
        self.source = source or ""
        self.file_path = file_path

    @abstractmethod
    def cyclomatic_complexity(self) -> int:
        """McCabe cyclomatic complexity: base 1 plus one per decision point."""

    @abstractmethod
    def ast_depth(self) -> int:
        """Maximum nesting depth of the syntax tree (root counts as depth 1)."""

    @abstractmethod
    def detected_libraries(self) -> dict[str, float]:
        """``{library: reference_intensity}`` for registry libraries only."""

    @abstractmethod
    def library_usage(self) -> dict[str, dict]:
        """Rich per-library facts: ``{lib: {call_sites, kernel_authoring}}``."""

    @abstractmethod
    def is_boilerplate(self, commit_context: str = "") -> bool:
        """True when the file is scaffolding/generated rather than real logic."""

    # -- shared helpers -----------------------------------------------------
    def _has_generated_marker(self) -> bool:
        head = self.source[:4000].lower()
        return any(marker in head for marker in _GENERATED_MARKERS)

    @staticmethod
    def _commit_suggests_boilerplate(commit_context: str) -> bool:
        if not commit_context:
            return False
        ctx = commit_context.lower()
        return any(token in ctx for token in _BOILERPLATE_COMMIT_TOKENS)

    def _significant_line_count(self) -> int:
        """Count non-blank, non-comment lines (language-agnostic approximation)."""
        count = 0
        for raw in self.source.splitlines():
            line = raw.strip()
            if not line:
                continue
            if line.startswith(("#", "//", "*", "/*", "*/")):
                continue
            count += 1
        return count


# ---------------------------------------------------------------------------
# Python (native ast)
# ---------------------------------------------------------------------------
class PythonParser(BaseCodeParser):
    """AST-based parser for Python sources using the standard library."""

    # Decision nodes counted once each for cyclomatic complexity. Async variants
    # are included as direct equivalents of their synchronous forms.
    _DECISION_NODES = (
        ast.If,
        ast.For,
        ast.AsyncFor,
        ast.While,
        ast.With,
        ast.AsyncWith,
        ast.Try,
        ast.ExceptHandler,
        ast.IfExp,  # ternary expression `a if cond else b`
    )

    def __init__(self, source: str, file_path: str = "") -> None:
        super().__init__(source, file_path)
        # May raise SyntaxError on malformed input; callers (the engine) are
        # expected to catch parse failures and skip the file.
        self.tree = ast.parse(self.source)
        self._usage_cache: dict[str, dict] | None = None

    # -- complexity & depth -------------------------------------------------
    def cyclomatic_complexity(self) -> int:
        complexity = 1
        for node in ast.walk(self.tree):
            if isinstance(node, self._DECISION_NODES):
                complexity += 1
            elif isinstance(node, ast.BoolOp):
                # `a and b and c` is two decision points, hence len(values) - 1.
                complexity += len(node.values) - 1
        return complexity

    def ast_depth(self) -> int:
        def depth(node: ast.AST) -> int:
            children = list(ast.iter_child_nodes(node))
            if not children:
                return 1
            return 1 + max(depth(child) for child in children)

        return depth(self.tree)

    # -- library usage ------------------------------------------------------
    def _analyze_usage(self) -> dict[str, dict]:
        if self._usage_cache is not None:
            return self._usage_cache

        # name (local binding) -> canonical library
        bound_names: dict[str, str] = {}
        # local binding names that specifically refer to `autograd` from torch,
        # used to detect torch.autograd.Function subclasses.
        autograd_aliases: set[str] = set()
        # local binding names that refer directly to `Function` from torch.autograd.
        function_aliases: set[str] = set()

        for node in ast.walk(self.tree):
            if isinstance(node, ast.Import):
                for alias in node.names:
                    root = alias.name.split(".")[0]
                    lib = _resolve_lib(root)
                    if lib is None:
                        continue
                    bound = alias.asname or root
                    bound_names[bound] = lib
            elif isinstance(node, ast.ImportFrom):
                if not node.module:
                    continue  # relative import with no module root
                root = node.module.split(".")[0]
                lib = _resolve_lib(root)
                if lib is None:
                    continue
                is_autograd_mod = node.module.split(".")[-1] == "autograd"
                for alias in node.names:
                    bound = alias.asname or alias.name
                    bound_names[bound] = lib
                    if lib == "torch" and alias.name == "autograd":
                        autograd_aliases.add(bound)
                    if lib == "torch" and is_autograd_mod and alias.name == "Function":
                        function_aliases.add(bound)

        # Initialise usage records for every imported library.
        usage: dict[str, dict] = {
            lib: {"call_sites": 0, "kernel_authoring": False}
            for lib in set(bound_names.values())
        }

        # Count reference sites: each Load-context Name whose id is a bound alias.
        # Attribute chains (torch.cuda.foo) have exactly one root Name, so this
        # counts one reference per usage expression without double counting.
        for node in ast.walk(self.tree):
            if isinstance(node, ast.Name) and isinstance(node.ctx, ast.Load):
                lib = bound_names.get(node.id)
                if lib is not None:
                    usage[lib]["call_sites"] += 1

        # -- kernel authoring detection --------------------------------------
        for node in ast.walk(self.tree):
            if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
                for deco in node.decorator_list:
                    self._inspect_decorator(deco, bound_names, usage)
            elif isinstance(node, ast.ClassDef):
                for base in node.bases:
                    if self._is_torch_autograd_function(
                        base, bound_names, autograd_aliases, function_aliases
                    ):
                        usage.setdefault(
                            "torch", {"call_sites": 0, "kernel_authoring": False}
                        )
                        usage["torch"]["kernel_authoring"] = True

        self._usage_cache = usage
        return usage

    @staticmethod
    def _decorator_target(deco: ast.expr) -> ast.expr:
        # `@triton.jit()` -> unwrap the Call to its func; `@triton.jit` stays.
        return deco.func if isinstance(deco, ast.Call) else deco

    def _inspect_decorator(
        self,
        deco: ast.expr,
        bound_names: dict[str, str],
        usage: dict[str, dict],
    ) -> None:
        target = self._decorator_target(deco)

        # Attribute form: triton.jit / cuda.jit / numba.cuda.jit
        if isinstance(target, ast.Attribute) and target.attr == "jit":
            value = target.value
            if isinstance(value, ast.Name):
                lib = bound_names.get(value.id)
                if lib in ("triton", "cuda"):
                    self._flag_kernel(usage, lib)
            elif isinstance(value, ast.Attribute) and value.attr == "cuda":
                # numba.cuda.jit — treat as CUDA kernel authoring.
                self._flag_kernel(usage, "cuda")
        # Bare-name form: `from triton import jit` then `@jit`.
        elif isinstance(target, ast.Name):
            lib = bound_names.get(target.id)
            if lib in ("triton",) and target.id in ("jit",):
                self._flag_kernel(usage, lib)

    @staticmethod
    def _flag_kernel(usage: dict[str, dict], lib: str) -> None:
        usage.setdefault(lib, {"call_sites": 0, "kernel_authoring": False})
        usage[lib]["kernel_authoring"] = True

    @staticmethod
    def _is_torch_autograd_function(
        base: ast.expr,
        bound_names: dict[str, str],
        autograd_aliases: set[str],
        function_aliases: set[str],
    ) -> bool:
        # torch.autograd.Function
        if (
            isinstance(base, ast.Attribute)
            and base.attr == "Function"
            and isinstance(base.value, ast.Attribute)
            and base.value.attr == "autograd"
            and isinstance(base.value.value, ast.Name)
            and bound_names.get(base.value.value.id) == "torch"
        ):
            return True
        # autograd.Function  (from torch import autograd)
        if (
            isinstance(base, ast.Attribute)
            and base.attr == "Function"
            and isinstance(base.value, ast.Name)
            and base.value.id in autograd_aliases
        ):
            return True
        # Function  (from torch.autograd import Function)
        if isinstance(base, ast.Name) and base.id in function_aliases:
            return True
        return False

    def library_usage(self) -> dict[str, dict]:
        return self._analyze_usage()

    def detected_libraries(self) -> dict[str, float]:
        return {
            lib: float(facts["call_sites"])
            for lib, facts in self._analyze_usage().items()
        }

    # -- boilerplate --------------------------------------------------------
    def is_boilerplate(self, commit_context: str = "") -> bool:
        if not self.source.strip():
            return True
        if self._has_generated_marker():
            return True

        complexity = self.cyclomatic_complexity()

        # Structural triviality: only imports, simple assignments, docstrings,
        # pass/ellipsis, and (re-export) __all__ at the top level, with no real
        # branching. Typical of __init__.py re-export shims and config stubs.
        trivial_body = self._is_structurally_trivial()

        if trivial_body and complexity <= 1:
            return True

        # A weak commit-message hint only tips low-complexity files over.
        if self._commit_suggests_boilerplate(commit_context) and complexity <= 2:
            return True

        return False

    def _is_structurally_trivial(self) -> bool:
        has_logic_def = False
        for node in self.tree.body:
            if isinstance(node, (ast.Import, ast.ImportFrom)):
                continue
            if isinstance(node, ast.Assign):
                continue
            if isinstance(node, ast.AnnAssign):
                continue
            if isinstance(node, ast.Expr) and isinstance(
                node.value, ast.Constant  # docstrings / bare literals
            ):
                continue
            if isinstance(node, (ast.Pass,)):
                continue
            if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef)):
                # A def/class with a non-trivial body means real code.
                if not self._is_trivial_block(node):
                    has_logic_def = True
                continue
            # Any other top-level statement (if/for/while/with/return/...) is logic.
            return False
        return not has_logic_def

    @staticmethod
    def _is_trivial_block(node: ast.AST) -> bool:
        body = getattr(node, "body", [])
        for stmt in body:
            if isinstance(stmt, ast.Pass):
                continue
            if isinstance(stmt, ast.Expr) and isinstance(
                stmt.value, ast.Constant
            ):
                continue  # docstring / `...`
            if isinstance(stmt, ast.Raise):
                # e.g. `raise NotImplementedError` — an abstract stub.
                continue
            return False
        return True


# ---------------------------------------------------------------------------
# Tree-sitter (cpp / javascript / typescript / tsx)
# ---------------------------------------------------------------------------

# Node types counted as decision points across the tree-sitter grammars. Loop
# and conditional variants are included as equivalents of Python's set.
_TS_DECISION_NODES = frozenset(
    {
        "if_statement",
        "for_statement",
        "for_in_statement",
        "for_range_loop",
        "while_statement",
        "do_statement",
        "catch_clause",
        "case_statement",
        "switch_case",
        "ternary_expression",
        "conditional_expression",
    }
)

# CUDA authoring markers detected lexically for .cu/.cpp sources. These are
# language keywords/operators that only appear when authoring device code.
_CUDA_KERNEL_MARKERS = ("__global__", "__device__", "<<<")


@lru_cache(maxsize=None)
def _load_language(language: str):
    """Load and cache a tree-sitter ``Language`` for the given identifier.

    Imports are performed lazily so that Python-only analysis does not require
    the tree-sitter native grammars to be installed.
    """
    try:
        from tree_sitter import Language
    except ImportError as exc:  # pragma: no cover - environment dependent
        raise ImportError(
            "py-tree-sitter is required for non-Python parsing. "
            "Install it with `pip install tree-sitter`."
        ) from exc

    try:
        if language == "cpp":
            import tree_sitter_cpp as ts_lang
            return Language(ts_lang.language())
        if language == "javascript":
            import tree_sitter_javascript as ts_lang
            return Language(ts_lang.language())
        if language == "typescript":
            import tree_sitter_typescript as ts_lang
            return Language(ts_lang.language_typescript())
        if language == "tsx":
            import tree_sitter_typescript as ts_lang
            return Language(ts_lang.language_tsx())
    except ImportError as exc:  # pragma: no cover - environment dependent
        raise ImportError(
            f"Missing tree-sitter grammar for '{language}'. Install the matching "
            f"`tree-sitter-{language.replace('tsx', 'typescript')}` package."
        ) from exc

    raise ValueError(f"Unsupported tree-sitter language: {language!r}")


class TreeSitterParser(BaseCodeParser):
    """py-tree-sitter parser for C/C++/CUDA, JavaScript, and TypeScript."""

    def __init__(self, source: str, language: str, file_path: str = "") -> None:
        super().__init__(source, file_path)
        self.language = language
        from tree_sitter import Parser  # local import: optional dependency

        self._lang = _load_language(language)
        self._parser = Parser(self._lang)
        self._source_bytes = self.source.encode("utf-8")
        self.tree = self._parser.parse(self._source_bytes)
        self._usage_cache: dict[str, dict] | None = None

    # -- query helper -------------------------------------------------------
    def _query_captures(self, query_str: str) -> dict[str, list]:
        from tree_sitter import Query, QueryCursor

        query = Query(self._lang, query_str)
        cursor = QueryCursor(query)
        return cursor.captures(self.tree.root_node)

    def _node_text(self, node) -> str:
        return self._source_bytes[node.start_byte : node.end_byte].decode(
            "utf-8", errors="replace"
        )

    # -- complexity & depth -------------------------------------------------
    def cyclomatic_complexity(self) -> int:
        complexity = 1
        root = self.tree.root_node
        stack = [root]
        while stack:
            node = stack.pop()
            if node.type in _TS_DECISION_NODES:
                complexity += 1
            elif node.type == "binary_expression":
                op = node.child_by_field_name("operator")
                if op is not None and self._node_text(op) in ("&&", "||"):
                    complexity += 1
            stack.extend(node.children)
        return complexity

    def ast_depth(self) -> int:
        def depth(node) -> int:
            # Consider only named children so that punctuation tokens (braces,
            # semicolons) do not inflate the measured nesting depth.
            named = [c for c in node.children if c.is_named]
            if not named:
                return 1
            return 1 + max(depth(child) for child in named)

        return depth(self.tree.root_node)

    # -- library usage ------------------------------------------------------
    def _analyze_usage(self) -> dict[str, dict]:
        if self._usage_cache is not None:
            return self._usage_cache

        bound_names: dict[str, str] = {}   # local identifier -> library
        import_ranges: list[tuple[int, int]] = []

        self._collect_imports(bound_names, import_ranges)

        usage: dict[str, dict] = {
            lib: {"call_sites": 0, "kernel_authoring": False}
            for lib in set(bound_names.values())
        }

        # Count identifier references that fall outside import statements.
        if bound_names:
            captures = self._query_captures("(identifier) @id")
            for node in captures.get("id", []):
                name = self._node_text(node)
                lib = bound_names.get(name)
                if lib is None:
                    continue
                if self._within_ranges(node.start_byte, import_ranges):
                    continue
                usage[lib]["call_sites"] += 1

        # CUDA kernel authoring (device code) is detected lexically for C++.
        if self.language == "cpp" and any(
            marker in self.source for marker in _CUDA_KERNEL_MARKERS
        ):
            usage.setdefault("cuda", {"call_sites": 0, "kernel_authoring": False})
            usage["cuda"]["kernel_authoring"] = True

        self._usage_cache = usage
        return usage

    def _collect_imports(
        self,
        bound_names: dict[str, str],
        import_ranges: list[tuple[int, int]],
    ) -> None:
        # ES module imports: `import express from 'express'`,
        # `import * as ex from 'express'`, `import { Router } from 'express'`.
        try:
            import_caps = self._query_captures(
                "(import_statement) @imp"
            )
        except Exception:
            import_caps = {}
        for node in import_caps.get("imp", []):
            source_node = node.child_by_field_name("source")
            module = None
            if source_node is not None:
                module = self._string_literal_value(source_node)
            if module is None:
                # Fall back: last string child.
                strings = [c for c in node.children if c.type == "string"]
                if strings:
                    module = self._string_literal_value(strings[-1])
            if not module:
                continue
            lib = _resolve_lib(module.split("/")[0])
            if lib is None:
                continue
            import_ranges.append((node.start_byte, node.end_byte))
            for ident in self._descendant_identifiers(node):
                if self._node_text(ident) != module:
                    bound_names[self._node_text(ident)] = lib
            # Also bind the module base name itself (default import commonly
            # shares the package name, e.g. `import express from 'express'`).
            bound_names.setdefault(module.split("/")[0], lib)

        # CommonJS: `const express = require('express')`.
        try:
            require_caps = self._query_captures(
                """
                (call_expression
                  function: (identifier) @fn
                  arguments: (arguments (string) @arg))
                """
            )
        except Exception:
            require_caps = {}
        fns = require_caps.get("fn", [])
        args = require_caps.get("arg", [])
        for fn_node, arg_node in zip(fns, args):
            if self._node_text(fn_node) != "require":
                continue
            module = self._string_literal_value(arg_node)
            if not module:
                continue
            lib = _resolve_lib(module.split("/")[0])
            if lib is None:
                continue
            # Bind the enclosing declarator identifier, if present.
            decl = self._enclosing_declarator_name(arg_node)
            if decl:
                bound_names[decl] = lib
                import_ranges.append(
                    self._declaration_range(arg_node)
                )

        # C/C++ #include lines are not library imports in the registry sense;
        # CUDA authoring is handled by the lexical marker scan instead.

    def _string_literal_value(self, node) -> str | None:
        text = self._node_text(node)
        # Strip surrounding quotes (single, double, or backtick).
        if len(text) >= 2 and text[0] in "\"'`" and text[-1] == text[0]:
            return text[1:-1]
        # `string` nodes sometimes wrap a `string_fragment` child.
        for child in node.children:
            if child.type in ("string_fragment", "string_content"):
                return self._node_text(child)
        return None

    def _descendant_identifiers(self, node) -> list:
        found = []
        stack = list(node.children)
        while stack:
            n = stack.pop()
            if n.type == "identifier":
                found.append(n)
            stack.extend(n.children)
        return found

    def _enclosing_declarator_name(self, node) -> str | None:
        cur = node.parent
        while cur is not None:
            if cur.type == "variable_declarator":
                name_node = cur.child_by_field_name("name")
                if name_node is not None and name_node.type == "identifier":
                    return self._node_text(name_node)
            cur = cur.parent
        return None

    def _declaration_range(self, node) -> tuple[int, int]:
        cur = node.parent
        while cur is not None:
            if cur.type in (
                "variable_declaration",
                "lexical_declaration",
                "expression_statement",
            ):
                return (cur.start_byte, cur.end_byte)
            cur = cur.parent
        return (node.start_byte, node.end_byte)

    @staticmethod
    def _within_ranges(byte_pos: int, ranges: list[tuple[int, int]]) -> bool:
        return any(start <= byte_pos < end for start, end in ranges)

    def library_usage(self) -> dict[str, dict]:
        return self._analyze_usage()

    def detected_libraries(self) -> dict[str, float]:
        return {
            lib: float(facts["call_sites"])
            for lib, facts in self._analyze_usage().items()
        }

    # -- boilerplate --------------------------------------------------------
    def is_boilerplate(self, commit_context: str = "") -> bool:
        if not self.source.strip():
            return True
        if self._has_generated_marker():
            return True

        # A parse dominated by ERROR nodes is not meaningfully analyzable; treat
        # it as non-boilerplate so broken files are not silently up-weighted.
        complexity = self.cyclomatic_complexity()
        significant = self._significant_line_count()

        # Structural triviality for curly-brace languages: only imports/exports
        # and top-level declarations with no control flow.
        trivial = self._is_structurally_trivial()
        if trivial and complexity <= 1:
            return True

        if self._commit_suggests_boilerplate(commit_context) and complexity <= 2:
            return True

        # Extremely small files with no branching (e.g. a re-export barrel).
        if complexity <= 1 and significant <= 3:
            return True

        return False

    def _is_structurally_trivial(self) -> bool:
        # Top-level children that are purely imports/exports/comments count as
        # non-logic. Any control-flow anywhere disqualifies triviality.
        root = self.tree.root_node
        control_present = False
        stack = [root]
        while stack:
            node = stack.pop()
            if node.type in _TS_DECISION_NODES or node.type == "binary_expression":
                if node.type == "binary_expression":
                    op = node.child_by_field_name("operator")
                    if op is not None and self._node_text(op) in ("&&", "||"):
                        control_present = True
                else:
                    control_present = True
            stack.extend(node.children)
        if control_present:
            return False

        non_trivial_top = 0
        for child in root.children:
            if not child.is_named:
                continue
            if child.type in (
                "import_statement",
                "comment",
                "preproc_include",
                "export_statement",
            ):
                continue
            non_trivial_top += 1
        return non_trivial_top == 0


# ---------------------------------------------------------------------------
# Factory
# ---------------------------------------------------------------------------
def get_parser(file_path: str, source: str) -> BaseCodeParser:
    """Return the appropriate parser for *file_path* based on its extension.

    Raises :class:`ValueError` for unsupported extensions and may propagate
    :class:`SyntaxError` (Python) if *source* cannot be parsed.
    """
    ext = os.path.splitext(file_path)[1].lower()
    language = _EXT_LANGUAGE.get(ext)
    if language is None:
        raise ValueError(f"Unsupported file extension for parsing: {ext!r}")

    if language == "python":
        return PythonParser(source, file_path=file_path)
    return TreeSitterParser(source, language=language, file_path=file_path)
